name: Tests
on:
  push:
    branches: [dev]

jobs:

  run-tests:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v2
        with:
          repository: johnshift/multirepo-frontend
          ref: 'dev'
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'pnpm'
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.16.1
          run_install: true
      - name: Run Format and Lint
        run: pnpm format && pnpm lint
      - name: Run Unit Tests
        run: pnpm test:unit
      - name: "TODO: Run Integration Test"
        run: echo "..."

  # trigger-workflow:
  #   name: Trigger Workflow
  #   needs: [run-tests]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger Workflow of Main Repo
  #       uses: peter-evans/repository-dispatch@v1
  #       with:
  #         token: ${{ secrets.PAT }}
  #         repository: johnshift/multirepo-cicd
  #         event-type: frontend
  #         client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "ref-repo": "${{ github.repository }}"}'

  # merge-to-main:
  #   name: Merge dev branch to main
  #   runs-on: ubuntu-latest
  #   needs: [run-tests]
  #   steps:
  #     - name: Checkout Branch
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #         token: ${{ secrets.PAT }}
  #     - uses: fregante/setup-git-user@v1
  #     - name: Merge
  #       run: |
  #         git checkout main
  #         git merge dev --commit -m 'merge dev -> main' 
  #         git push origin main