name: Dispatch 
on:
  push:
    branches: [main]

jobs:

  trigger-workflow:
    name: Trigger Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow of Main Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: johnshift/multirepo-cicd
          event-type: frontend-main
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "ref-repo": "${{ github.repository }}"}'